# Prior/Anchor box configuration for SSD 300x300

priors:
  image_size: [300, 300]
  strides: [8, 16, 32, 64, 128, 224]
  
  aspect_ratios:
    - [1.0, 2.0, 0.5]
    - [1.0, 2.0, 0.5, 3.0, 0.3333]
    - [1.0, 2.0, 0.5, 3.0, 0.3333]
    - [1.0, 2.0, 0.5]
    - [1.0, 2.0, 0.5]
    - [1.0, 2.0, 0.5]

  min_scale: 0.2
  max_scale: 0.95
  variances: [0.1, 0.2]
